name: flutter_piper_tts_example
description: "Demonstrates how to use the flutter_piper_tts package."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_piper_tts:
    path: ../
  cupertino_icons: ^1.0.8
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
