name: flutter_piper_tts
description: "TTS in Flutter using Piper TTS models + audio player in one package."
version: 0.4.1
repository: https://github.com/dikatok/flutter_piper_tts
topics: [tts, audio, flutter]

environment:
  sdk: ^3.11.5
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  dart_piper_tts: ^0.2.0
  android_libcpp_shared: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# flutter:
#   assets:
#     - assets/phonemizer/g2p-mbyt5-12l-ipa-childes-espeak-onnx-quantized.onnx
