name: flutter_piper_tts
description: "TTS in Flutter using Piper TTS models + audio player in one package."
version: 0.0.1
repository: https://github.com/dikatok/flutter_piper_tts
topics: [ tts, audio, flutter ]

environment:
  sdk: ^3.11.5
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  android_libcpp_shared: ^0.1.1
  dart_piper_tts: ^0.1.0
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

